name: shop
main: jp.fishnetwork.shop.Main
version: 1.0.0
api-version: 1.19
depend: [floodgate, Vault]
commands:
  shop:
    description: Open the shop
    permission: shop.command
permissions:
  shop.command:
    description: Use /shop command
    default: true